Remove flutter_export_environment.sh
schibsted/tweet_ui pull request #70
Opened 2021-09-10 20:43 UTC by ndahlquist

According to the comment, this should not be checked into git.

2021-09-13 06:25 UTC, kawa89 approved these changes

2021-09-13 06:26 UTC, kawa89 requested changes
I think you need to add a rule in the .gitignore file to not track this file.

2021-09-13 06:26 UTC, kawa89 commented
Nice catch BTW ;)

2021-09-15 02:53 UTC, ndahlquist commented
Actually, this is is already in the .gitignore here! https://github.com/schibsted/tweet_ui/blob/dev/.gitignore#L41.

Not sure how it got checked in originally, but it after removing it, it is not showing up as dirty.

2021-09-28 13:38 UTC, kawa89 approved these changes

2021-09-28 13:38 UTC, merged